spring:
    application:
        name: findog
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://findog-mysql.cxgc0qkqmops.ap-northeast-2.rds.amazonaws.com:3306/findog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: root1234
    jpa:
        hibernate:
            ddl-auto: update

cloud:
    aws:
        s3:
            bucket: findog
            credentials:
                access-key: AKIA47SBDGN2JTPKYQOS
                secret-key: 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
        region:
            static: ap-northeast-2
            auto: false
        stack:
            auto: false

jwt:
    secret: d8e5a4bab049a69f7eecfeb2271ffff2c39dda064a27ea26ba7bd271b30e1734